### ISSUE TITLE
Requirements benoemen & indelen

### ISSUE THREAD

**Issue by rijnswou** [Groeboe/Oefenproject-ITANN#32]
Welk probleem proberen we op te lossen of wat kunnen we toevoegen als meerwaarde?
Omschrijf de eisen waar de app aan móet voldoen.

**Comment by marikevisser** [comment]
Ik heb in de wiki-omgeving een voorstel gezet om de requirement-issues in te delen volgens de MoSCoW-methode. 

https://github.com/Groeboe/Oefenproject-ITANN.wiki.git

**Comment by rijnswou** [comment]
Top!
Aan de hand het artikel hebben we de requirements besproken en de betreffende labels toegevoegd aan de issues.

**Comment by rijnswou** [comment]
Tom merkte terecht op dat we nu voornamelijk functionele requirements hebben genoemd. Volgens het FURPS model kunnen we dit aanvullen met:
Usability
Reliability
Performance
Supportability

Dit noteer ik als agendapunt voor de volgende meeting.
