### ISSUE TITLE
Omschrijf de app

### ISSUE THREAD

**Issue by rijnswou** [Groeboe/Oefenproject-ITANN#33]
In gewone mensentaal. Hoe gaan mensen de app gebruiken en waarvoor?
Hier kunnen we gebruik maken van use cases of user stories.

**Comment by marikevisser** [comment]
Afspraken: iedereen maakt een user-case van twee must-have-issues. We schrijven deze user-cases IN de bijbehorende issues.

**Comment by marikevisser** [comment]
Tom maakt een algemene omschrijving van de app. In een wiki.

**Comment by Tsluiz** [comment]
**[Abstracte User Story = Bezoeker]** 
Als een dagelijkse bezoeker van het Noorderzon festival wil ik me goed kunnen voorbereiden door van het gehele programma een programma te maken dat bij mij past. Ik wil dit programma op m'n mobiel hebben zodat ik elk moment mijn programma kan raadplegen, maar ook het laatste (social media/weer-) nieuws over het festival op een plek kan lezen. Voor, tijdens en na het festival wil ik vanuit de app mijn plannen, ervaringen en meningen uitwisselen met mijn vrienden en mede-noorderzon liefhebbers. Per tekst of foto. Bovendien wil ik mijn entree bewijzen in m'n mobiel bewaren zodat ik en de kaarten-controleurs kunnen zien waar ik heb gereserveerd. Als Noorderzon liefhebber sta ik open voor verrassingen en vind ik het leuk om op creatieve wijze interactie te hebben. Als ik kan laten zien dat ik van alle bezoekers toch wel een van de Echte trouwe oplettende Noorderzonners ben en bijvoorbeeld daarmee drank-punten kan verzamelen, dan is de app helemaal perfect.

**[Abstracte User Story = Exposant]** 
Als een exposant (programma onderdeel/eettentje) wil ik via m'n mobiel, tablet of desktop mijn aanbod goed onder het voetlicht brengen bij mogelijke bezoekers. Ik wil weten wie mijn aanbod leuk vinden, wie welke kaartjes of bonnen kopen en wat de afnemers van mijn aanbod hebben gevonden. Op basis van gegevens van de bezoekers zou ik extra aanbiedingen of updates kunnen doorgeven via de app. Na het festival wil ik als exposant een overzicht van deze totalen: aantal likes, alle reviews, de verkochte bonnen/kaartjes.

(n.t.b. of dit er nog bij komt:)**[Abstracte User Story = Organisator]**  
Als organisator van het Noorderzon festival wil ik kunnen zien wie het festival leuk vinden en wat er op elk moment speelt omtrent het festival. Ook wil ik op basis van gegevens kunnen zien wat de verwachte drukte per avond is en in hoeverre programma onderdelen geboekt zijn. De app is voor de organisatie bovendien het kanaal om alle gebruikers te informeren over o.a. calamiteiten. Na het festival wil ik als organisator een totaal overzicht van alle exposanten en hun totalen: aantal likes, alle reviews, de verkochte bonnen/kaartjes.


zet ik ook in een wiki. zie wiki
