### ISSUE TITLE
Omschrijf de belangrijkste objecten

### ISSUE THREAD

**Issue by rijnswou** [Groeboe/Oefenproject-ITANN#34]
De belangrijkste ideeën en concepten voor de app omzetten in objecten.
Focus op belangrijke dingen (dus nog niet de nice-to-haves)

**Comment by marikevisser** [comment]
Hiervoor hebben we een wiki gemaakt:
https://github.com/Groeboe/Oefenproject-ITANN.wiki.git 

Iedereen beschrijft de objecten die voorkomen in de issues waar hij/zij de user-story van schrijft.
